### ISSUE TITLE
删除任务时链表更新有问题

### ISSUE THREAD

**Issue by liangyang001** [ouqiang/timewheel#3]
如果key命中  应该在l.Remote(e)后break吧  后面的e=e.Next()也没意义

**Comment by ouqiang** [comment]
当执行l.remove(e)时,  e.Next会被设置为nil, 不会继续往下执行。

**Comment by liangyang001** [comment]
@ouqiang 
e.Next()确实是会返回nil   不过代码读起来貌似违反直觉  (PS:其它语言转过来的)

**Comment by ouqiang** [comment]
利用了Go的"坑"
