### ISSUE TITLE
回调函数参数为什么是map？

### ISSUE THREAD

**Issue by chenqinghe** [ouqiang/timewheel#4]
为什么不是interface{} ? 感觉interface{}更加通用啊

**Comment by ouqiang** [comment]
方便定时器加入一些元数据信息, 供调用者使用

**Comment by cute-angelia** [comment]
回调函数, 应该是用户自定义闭包啊, 这样才灵活, 直接限制为 map... 很多事情处理不了

**Comment by ouqiang** [comment]
已改为 interface{}
